version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bookstore_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: openjdk:17-jdk
    working_dir: /app
    volumes:
      - ./:/app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
