spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookstore}
    username: ${SPRING_DATASOURCE_USERNAME:bookstore_user}
    password: ${SPRING_DATASOURCE_PASSWORD:supersecret}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  docker:
    compose:
      enabled: false


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    connect-retries: 5

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: moj-super-tajny-klucz-jwt-123456
  expirationMs: 86400000
