spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore_user
    password: supersecret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:moj-super-tajny-klucz-jwt-123456}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
